# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.equipment_producer:
        class: App\Admin\EquipmentProducerAdmin
        arguments: [~, App\Entity\EquipmentProducer, App\Controller\EquipmentProducerAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EquipmentProducer }
        public: true

    admin.equipment_type:
        class: App\Admin\EquipmentTypeAdmin
        arguments: [~, App\Entity\EquipmentType, App\Controller\EquipmentTypeAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EquipmentType }
        public: true

    admin.interval:
        class: App\Admin\IntervalAdmin
        arguments: [~, App\Entity\Interval, App\Controller\IntervalAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Interval }
        public: true

    admin.preservative_material_unit:
        class: App\Admin\PreservativeMaterialUnitAdmin
        arguments: [~, App\Entity\PreservativeMaterialUnit, App\Controller\PreservativeMaterialUnitAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: PreservativeMaterialUnit }
        public: true

    admin.preservative_material:
        class: App\Admin\PreservativeMaterialAdmin
        arguments: [~, App\Entity\PreservativeMaterial, App\Controller\PreservativeMaterialAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: PreservativeMaterial }
        public: true

    admin.preservative_product:
        class: App\Admin\PreservativeProductAdmin
        arguments: [~, App\Entity\PreservativeProduct, App\Controller\PreservativeProductAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: PreservativeProduct }
        public: true

    admin.equipment:
        class: App\Admin\EquipmentAdmin
        arguments: [~, App\Entity\Equipment, App\Controller\EquipmentAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Equipment }
        public: true
